export interface LocalizedSurahInfo {
  name: string;
  meaning: string;
}

export const SURAH_LOCALIZED_DATA: Record<number, Record<string, LocalizedSurahInfo>> = {
  1: {
    hi: { name: "अल-फ़ातिहा", meaning: "आरंभ / प्रस्तावना" },
    ru: { name: "Аль-Фатиха", meaning: "Открывающая Книгу" },
    ur: { name: "الفاتحہ", meaning: "شروع کرنے والی" },
    bn: { name: "আল-ফাতিহা", meaning: "সূচনা" },
    id: { name: "Al-Fatihah", meaning: "Pembukaan" },
    ms: { name: "Al-Fatihah", meaning: "Pembukaan" },
  },
  2: {
    hi: { name: "अल-बक़रह", meaning: "गाय" },
    ru: { name: "Аль-Бакара", meaning: "Корова" },
    ur: { name: "البقرہ", meaning: "گائے" },
    bn: { name: "আল-বাকারা", meaning: "গাভী" },
    id: { name: "Al-Baqarah", meaning: "Sapi Betina" },
    ms: { name: "Al-Baqarah", meaning: "Lembu Betina" },
  },
  3: {
    hi: { name: "आलि इमरान", meaning: "इमरान का परिवार" },
    ru: { name: "Али Имран", meaning: "Семейство Имрана" },
    ur: { name: "آل عمران", meaning: "عمران کی آل" },
    bn: { name: "আলে ইমরান", meaning: "ইমরানের পরিবার" },
    id: { name: "Ali 'Imran", meaning: "Keluarga Imran" },
    ms: { name: "Ali 'Imran", meaning: "Keluarga Imran" },
  },
  4: {
    hi: { name: "अन-निसा", meaning: "महिलाएं" },
    ru: { name: "Ан-Ниса", meaning: "Женщины" },
    ur: { name: "النساء", meaning: "عورتیں" },
    bn: { name: "আন-নিসা", meaning: "নারী" },
    id: { name: "An-Nisa'", meaning: "Wanita" },
    ms: { name: "An-Nisa'", meaning: "Wanita" },
  },
  5: {
    hi: { name: "अल-माइदा", meaning: "सजा हुआ दस्तरख़्वान" },
    ru: { name: "Аль-Маида", meaning: "Трапеза" },
    ur: { name: "المائدہ", meaning: "دسترفوان" },
    bn: { name: "আল-মায়িদাহ", meaning: "খাদ্য পরিবেশিত টেবিল" },
    id: { name: "Al-Ma'idah", meaning: "Hidangan Makanan" },
    ms: { name: "Al-Ma'idah", meaning: "Hidangan" },
  },
  6: {
    hi: { name: "अल-अनआम", meaning: "मवेशी" },
    ru: { name: "Аль-Ан'ам", meaning: "Скот" },
    ur: { name: "الانعام", meaning: "چوپائے" },
    bn: { name: "আল-আন'আম", meaning: "গৃহপালিত পশু" },
    id: { name: "Al-An'am", meaning: "Binatang Ternak" },
    ms: { name: "Al-An'am", meaning: "Binatang Ternak" },
  },
  7: {
    hi: { name: "अल-अअराफ़", meaning: "ऊंचाइयां" },
    ru: { name: "Аль-А'раф", meaning: "Преграды" },
    ur: { name: "الاعراف", meaning: "بلندیاں" },
    bn: { name: "আল-আ'রাফ", meaning: "উঁচু স্থান" },
    id: { name: "Al-A'raf", meaning: "Tempat yang Tertinggi" },
    ms: { name: "Al-A'raf", meaning: "Tempat Tertinggi" },
  },
  8: {
    hi: { name: "अल-अनफ़ाल", meaning: "युद्ध की संपत्ति" },
    ru: { name: "Аль-Анфаль", meaning: "Трофеи" },
    ur: { name: "الانفال", meaning: "غنیمت" },
    bn: { name: "আল-আনফাল", meaning: "যুদ্ধলব্ধ সম্পদ" },
    id: { name: "Al-Anfal", meaning: "Rampasan Perang" },
    ms: { name: "Al-Anfal", meaning: "Harta Rampasan Perang" },
  },
  9: {
    hi: { name: "अत-तौबा", meaning: "तौबा / क्षमा" },
    ru: { name: "Ат-Тауба", meaning: "Покаяние" },
    ur: { name: "التوبہ", meaning: "توبہ" },
    bn: { name: "আত-তাওবাহ", meaning: "অনুশোচনা" },
    id: { name: "At-Taubah", meaning: "Pengampunan" },
    ms: { name: "At-Taubah", meaning: "Pengampunan" },
  },
  10: {
    hi: { name: "यूनुस", meaning: "हज़रत यूनुस" },
    ru: { name: "Юнус", meaning: "Иона" },
    ur: { name: "یونس", meaning: "یونس علیہ السلام" },
    bn: { name: "ইউনুস", meaning: "ইউনূস (আঃ)" },
    id: { name: "Yunus", meaning: "Nabi Yunus" },
    ms: { name: "Yunus", meaning: "Nabi Yunus" },
  },
  11: {
    hi: { name: "हूद", meaning: "हज़रत हूद" },
    ru: { name: "Худ", meaning: "Худ" },
    ur: { name: "ہود", meaning: "ہود علیہ السلام" },
    bn: { name: "হুদ", meaning: "হূদ (আঃ)" },
    id: { name: "Hud", meaning: "Nabi Hud" },
    ms: { name: "Hud", meaning: "Nabi Hud" },
  },
  12: {
    hi: { name: "यूसुफ़", meaning: "हज़रत यूसुफ़" },
    ru: { name: "Юсуф", meaning: "Иосиф" },
    ur: { name: "یوسف", meaning: "یوسف علیہ السلام" },
    bn: { name: "ইউসুফ", meaning: "ইউসুফ (আঃ)" },
    id: { name: "Yusuf", meaning: "Nabi Yusuf" },
    ms: { name: "Yusuf", meaning: "Nabi Yusuf" },
  },
  13: {
    hi: { name: "अर-रअद", meaning: "बिजली की कड़क" },
    ru: { name: "Ар-Ра'д", meaning: "Гром" },
    ur: { name: "الرعد", meaning: "گرج" },
    bn: { name: "আর-রাদ", meaning: "বজ্রপাত" },
    id: { name: "Ar-Ra'd", meaning: "Guruh" },
    ms: { name: "Ar-Ra'd", meaning: "Guruh" },
  },
  14: {
    hi: { name: "इब्राहीम", meaning: "हज़रत इब्राहीम" },
    ru: { name: "Ибрахим", meaning: "Авраам" },
    ur: { name: "ابراہیم", meaning: "ابراہیم علیہ السلام" },
    bn: { name: "ইব্রাহীম", meaning: "ইবরাহীম (আঃ)" },
    id: { name: "Ibrahim", meaning: "Nabi Ibrahim" },
    ms: { name: "Ibrahim", meaning: "Nabi Ibrahim" },
  },
  15: {
    hi: { name: "अल-हिज्र", meaning: "पथरीली घाटी" },
    ru: { name: "Аль-Хиджр", meaning: "Скалистые горы" },
    ur: { name: "الحجر", meaning: "حجر کی وادی" },
    bn: { name: "আল-হিজর", meaning: "পাথুরে পাহাড়" },
    id: { name: "Al-Hijr", meaning: "Daerah Pegunungan" },
    ms: { name: "Al-Hijr", meaning: "Kawasan Berbatu" },
  },
  16: {
    hi: { name: "अन-नह्ल", meaning: "मधुमक्खी" },
    ru: { name: "Ан-Нахль", meaning: "Пчелы" },
    ur: { name: "النحل", meaning: "شہد کی مکھی" },
    bn: { name: "আন-নাহল", meaning: "মৌমাছি" },
    id: { name: "An-Nahl", meaning: "Lebah" },
    ms: { name: "An-Nahl", meaning: "Lebah" },
  },
  17: {
    hi: { name: "अल-इस्रा", meaning: "रात्रि यात्रा" },
    ru: { name: "Аль-Исра", meaning: "Ночной перенос" },
    ur: { name: "الاسراء", meaning: "رات کا سفر" },
    bn: { name: "আল-ইসরা", meaning: "রাত্রিকালীন ভ্রমণ" },
    id: { name: "Al-Isra'", meaning: "Perjalanan Malam" },
    ms: { name: "Al-Isra'", meaning: "Perjalanan Malam" },
  },
  18: {
    hi: { name: "अल-कहफ़", meaning: "गुफा" },
    ru: { name: "Аль-Кахф", meaning: "Пещера" },
    ur: { name: "الکہف", meaning: "غار" },
    bn: { name: "আল-কাহফ", meaning: "গুহা" },
    id: { name: "Al-Kahf", meaning: "Gua" },
    ms: { name: "Al-Kahf", meaning: "Gua" },
  },
  19: {
    hi: { name: "मरयम", meaning: "हज़रत मरयम" },
    ru: { name: "Марьям", meaning: "Мария" },
    ur: { name: "مریم", meaning: "مریم علیہا السلام" },
    bn: { name: "মারইয়াম", meaning: "মরিয়ম" },
    id: { name: "Maryam", meaning: "Maryam" },
    ms: { name: "Maryam", meaning: "Siti Maryam" },
  },
  20: {
    hi: { name: "ता-हा", meaning: "ता-हा" },
    ru: { name: "Та Ха", meaning: "Та Ха" },
    ur: { name: "طٰہٰ", meaning: "طٰہٰ" },
    bn: { name: "ত্বা-হা", meaning: "ত্বা-হা" },
    id: { name: "Ta Ha", meaning: "Ta Ha" },
    ms: { name: "Ta Ha", meaning: "Ta Ha" },
  },
  21: {
    hi: { name: "अल-अंबिया", meaning: "पैग़ंबर" },
    ru: { name: "Аль-Анбийа", meaning: "Пророки" },
    ur: { name: "الانبیاء", meaning: "نبی" },
    bn: { name: "আল-আম্বিয়া", meaning: "নবীগণ" },
    id: { name: "Al-Anbiya'", meaning: "Nabi-Nabi" },
    ms: { name: "Al-Anbiya'", meaning: "Para Nabi" },
  },
  22: {
    hi: { name: "अल-हज", meaning: "हज (तीर्थयात्रा)" },
    ru: { name: "Аль-Хадж", meaning: "Паломничество" },
    ur: { name: "الحج", meaning: "حج" },
    bn: { name: "আল-হাজ্জ", meaning: "হজ" },
    id: { name: "Al-Hajj", meaning: "Haji" },
    ms: { name: "Al-Hajj", meaning: "Haji" },
  },
  23: {
    hi: { name: "अल-मोमिनून", meaning: "ईमान वाले" },
    ru: { name: "Аль-Му'минун", meaning: "Верующие" },
    ur: { name: "المؤمنون", meaning: "ایمان والے" },
    bn: { name: "আল-মু'মিনুন", meaning: "মুমিনগণ" },
    id: { name: "Al-Mu'minun", meaning: "Orang-Orang Mukmin" },
    ms: { name: "Al-Mu'minun", meaning: "Orang-Orang yang Beriman" },
  },
  24: {
    hi: { name: "अन-नूर", meaning: "प्रकाश / ज्योति" },
    ru: { name: "Ан-Нур", meaning: "Свет" },
    ur: { name: "النور", meaning: "روشنی" },
    bn: { name: "আন-নূর", meaning: "আলো" },
    id: { name: "An-Nur", meaning: "Cahaya" },
    ms: { name: "An-Nur", meaning: "Cahaya" },
  },
  25: {
    hi: { name: "अल-फ़ुरक़ान", meaning: "सत्य-असत्य का भेद" },
    ru: { name: "Аль-Фуркан", meaning: "Различение" },
    ur: { name: "الفرقان", meaning: "حق اور باطل کا فرق" },
    bn: { name: "আল-ফুরকান", meaning: "সত্য-মিথ্যার পার্থক্যকারী" },
    id: { name: "Al-Furqan", meaning: "Pembeda" },
    ms: { name: "Al-Furqan", meaning: "Pembeda Benar dan Salah" },
  },
  26: {
    hi: { name: "अश-शुअरा", meaning: "कवि" },
    ru: { name: "Аш-Шу'ара", meaning: "Поэты" },
    ur: { name: "الشعراء", meaning: "شاعر" },
    bn: { name: "আশ-শু'আরা", meaning: "কবিগণ" },
    id: { name: "Asy-Syu'ara'", meaning: "Penyair" },
    ms: { name: "Asy-Syu'ara'", meaning: "Para Penyair" },
  },
  27: {
    hi: { name: "अन-नम्ल", meaning: "चींटियां" },
    ru: { name: "Ан-Намль", meaning: "Муравьи" },
    ur: { name: "النمل", meaning: "چیونٹی" },
    bn: { name: "আন-নামল", meaning: "পিপীলিকা" },
    id: { name: "An-Naml", meaning: "Semut" },
    ms: { name: "An-Naml", meaning: "Semut" },
  },
  28: {
    hi: { name: "अल-क़सस", meaning: "वृत्तांत / कहानियां" },
    ru: { name: "Аль-Касас", meaning: "Рассказ" },
    ur: { name: "القصص", meaning: "قصے" },
    bn: { name: "আল-কাসাস", meaning: "কাহিনী" },
    id: { name: "Al-Qasas", meaning: "Kisah-Kisah" },
    ms: { name: "Al-Qasas", meaning: "Kisah-Kisah" },
  },
  29: {
    hi: { name: "अल-अनकबूत", meaning: "मकड़ी" },
    ru: { name: "Аль-'Анкабут", meaning: "Паук" },
    ur: { name: "العنکبوت", meaning: "مکڑی" },
    bn: { name: "আল-আনকাবুত", meaning: "মাকড়সা" },
    id: { name: "Al-'Ankabut", meaning: "Laba-Laba" },
    ms: { name: "Al-'Ankabut", meaning: "Labah-Labah" },
  },
  30: {
    hi: { name: "अर-रूम", meaning: "रोमन लोग" },
    ru: { name: "Ар-Рум", meaning: "Римляне" },
    ur: { name: "الروم", meaning: "اہلِ روم" },
    bn: { name: "আর-রুম", meaning: "রোমান জাতি" },
    id: { name: "Ar-Rum", meaning: "Bangsa Romawi" },
    ms: { name: "Ar-Rum", meaning: "Bangsa Rom" },
  },
  31: {
    hi: { name: "लुक़मान", meaning: "हज़रत लुक़मान" },
    ru: { name: "Лукман", meaning: "Лукман" },
    ur: { name: "لقمان", meaning: "لقمان حکیم" },
    bn: { name: "লুকমান", meaning: "লুকমান" },
    id: { name: "Luqman", meaning: "Luqman" },
    ms: { name: "Luqman", meaning: "Luqman" },
  },
  32: {
    hi: { name: "अस-सजदा", meaning: "सजदा" },
    ru: { name: "Ас-Саджда", meaning: "Земной поклон" },
    ur: { name: "السجدہ", meaning: "سجدہ" },
    bn: { name: "আস-সাজদাহ", meaning: "সিজদা" },
    id: { name: "As-Sajdah", meaning: "Sujud" },
    ms: { name: "As-Sajdah", meaning: "Sujud" },
  },
  33: {
    hi: { name: "अल-अहज़ाब", meaning: "संयुक्त सेनाएं" },
    ru: { name: "Аль-Ахзаб", meaning: "Союзники" },
    ur: { name: "الاحزاب", meaning: "لشکر" },
    bn: { name: "আল-আহযাব", meaning: "মিত্রবাহিনী" },
    id: { name: "Al-Ahzab", meaning: "Golongan yang Bersekutu" },
    ms: { name: "Al-Ahzab", meaning: "Golongan yang Bersekutu" },
  },
  34: {
    hi: { name: "सबा", meaning: "सबा की क़ौम" },
    ru: { name: "Саба", meaning: "Сава" },
    ur: { name: "سبا", meaning: "اہلِ سبا" },
    bn: { name: "সাবা", meaning: "সাবা জাতি" },
    id: { name: "Saba'", meaning: "Kaum Saba'" },
    ms: { name: "Saba'", meaning: "Kaum Saba'" },
  },
  35: {
    hi: { name: "फ़ातिर", meaning: "सृजनकर्ता" },
    ru: { name: "Фатыр", meaning: "Создатель" },
    ur: { name: "فاطر", meaning: "پیدا کرنے والا" },
    bn: { name: "ফাতির", meaning: "সৃষ্টিকর্তা" },
    id: { name: "Fatir", meaning: "Pencipta" },
    ms: { name: "Fatir", meaning: "Pencipta" },
  },
  36: {
    hi: { name: "या-सीन", meaning: "या-सीन" },
    ru: { name: "Йа Син", meaning: "Йа Син" },
    ur: { name: "یٰسٓ", meaning: "یٰسٓ" },
    bn: { name: "ইয়া-সীন", meaning: "ইয়া-সীন" },
    id: { name: "Ya Sin", meaning: "Ya Sin" },
    ms: { name: "Ya Sin", meaning: "Ya Sin" },
  },
  37: {
    hi: { name: "अस-साफ़्फ़ात", meaning: "पंक्तिबद्ध खड़े" },
    ru: { name: "Ас-Саффат", meaning: "Выстроившиеся в ряды" },
    ur: { name: "الصافات", meaning: "صف باندھنے والے" },
    bn: { name: "আস-সাফফাত", meaning: "সারিবদ্ধভাবে দণ্ডায়মান" },
    id: { name: "As-Saffat", meaning: "Barisan-Barisan" },
    ms: { name: "As-Saffat", meaning: "Yang Berbaris Rapi" },
  },
  38: {
    hi: { name: "साद", meaning: "साद" },
    ru: { name: "Сад", meaning: "Буква Сад" },
    ur: { name: "صٓ", meaning: "صٓ" },
    bn: { name: "সোয়াদ", meaning: "সোয়াদ" },
    id: { name: "Sad", meaning: "Sad" },
    ms: { name: "Sad", meaning: "Sad" },
  },
  39: {
    hi: { name: "अज़-ज़ुमर", meaning: "गिरोह / समूह" },
    ru: { name: "Аз-Зумар", meaning: "Толпы" },
    ur: { name: "الزمر", meaning: "گروہ" },
    bn: { name: "আজ-যুমার", meaning: "দলবদ্ধ জনতা" },
    id: { name: "Az-Zumar", meaning: "Rombongan" },
    ms: { name: "Az-Zumar", meaning: "Kumpulan-Kumpulan" },
  },
  40: {
    hi: { name: "ग़ाफ़िर", meaning: "क्षमा करने वाला" },
    ru: { name: "Гафир", meaning: "Прощающий" },
    ur: { name: "غافر", meaning: "بخشنے والا" },
    bn: { name: "গাফির", meaning: "ক্ষমাশীল" },
    id: { name: "Ghafir", meaning: "Yang Mengampuni" },
    ms: { name: "Ghafir", meaning: "Yang Mengampunkan" },
  },
  41: {
    hi: { name: "फ़ुस्सिलत", meaning: "सविस्तार स्पष्ट" },
    ru: { name: "Фуссылят", meaning: "Разъяснены" },
    ur: { name: "فصلت", meaning: "تفصیل سے بیان کی گئی" },
    bn: { name: "ফুসসিলাত", meaning: "সুস্পষ্ট বিবরণ" },
    id: { name: "Fussilat", meaning: "Yang Dijelaskan" },
    ms: { name: "Fussilat", meaning: "Dijelaskan dengan Terperinci" },
  },
  42: {
    hi: { name: "अश-शूरा", meaning: "परामर्श" },
    ru: { name: "Аш-Шура", meaning: "Совет" },
    ur: { name: "الشوریٰ", meaning: "مشورہ" },
    bn: { name: "আশ-শুরা", meaning: "পরামর্শ" },
    id: { name: "Asy-Syura", meaning: "Musyawarah" },
    ms: { name: "Asy-Syura", meaning: "Permesyuaratan" },
  },
  43: {
    hi: { name: "अज़-ज़ुख़रुफ़", meaning: "सोने के आभूषण" },
    ru: { name: "Аз-Зухруф", meaning: "Украшения" },
    ur: { name: "الزخرف", meaning: "سونے کا زیور" },
    bn: { name: "আজ-যুখরুফ", meaning: "স্বর্ণালঙ্কার" },
    id: { name: "Az-Zukhruf", meaning: "Perhiasan" },
    ms: { name: "Az-Zukhruf", meaning: "Perhiasan Emas" },
  },
  44: {
    hi: { name: "अद-दुख़ान", meaning: "धुआं" },
    ru: { name: "Ад-Духан", meaning: "Дым" },
    ur: { name: "الدخان", meaning: "دھواں" },
    bn: { name: "আদ-দুখান", meaning: "ধোঁয়া" },
    id: { name: "Ad-Dukhan", meaning: "Kabut / Asap" },
    ms: { name: "Ad-Dukhan", meaning: "Asap" },
  },
  45: {
    hi: { name: "अल-जासिया", meaning: "घुटने टेकने वाले" },
    ru: { name: "Аль-Джасийа", meaning: "Коленопреклоненные" },
    ur: { name: "الجاثیہ", meaning: "گھٹنوں کے بل گرے ہوئے" },
    bn: { name: "আল-জাসিয়াহ", meaning: "নতজানু" },
    id: { name: "Al-Jasiyah", meaning: "Yang Berlutut" },
    ms: { name: "Al-Jatsiyah", meaning: "Yang Berlutut" },
  },
  46: {
    hi: { name: "अल-अहक़ाफ़", meaning: "रेत के टीले" },
    ru: { name: "Аль-Ахкаф", meaning: "Барханы" },
    ur: { name: "الاحقاف", meaning: "ریت کے ٹیلے" },
    bn: { name: "আল-আহকাফ", meaning: "বালির পাহাড়" },
    id: { name: "Al-Ahqaf", meaning: "Bukit-Bukit Pasir" },
    ms: { name: "Al-Ahqaf", meaning: "Bukit Pasir" },
  },
  47: {
    hi: { name: "मुहम्मद", meaning: "हज़रत मुहम्मद ﷺ" },
    ru: { name: "Мухаммад", meaning: "Мухаммад" },
    ur: { name: "محمد", meaning: "محمد مصطفیٰ ﷺ" },
    bn: { name: "মুহাম্মদ", meaning: "মুহাম্মদ (সাঃ)" },
    id: { name: "Muhammad", meaning: "Nabi Muhammad" },
    ms: { name: "Muhammad", meaning: "Nabi Muhammad" },
  },
  48: {
    hi: { name: "अल-फ़तह", meaning: "विजय" },
    ru: { name: "Аль-Фатх", meaning: "Победа" },
    ur: { name: "الفتح", meaning: "فتح" },
    bn: { name: "আল-ফাতহ", meaning: "বিজয়" },
    id: { name: "Al-Fath", meaning: "Kemenangan" },
    ms: { name: "Al-Fath", meaning: "Kemenangan" },
  },
  49: {
    hi: { name: "अल-हुजुरात", meaning: "कक्ष / कमरे" },
    ru: { name: "Аль-Худжурат", meaning: "Комнаты" },
    ur: { name: "الحجرات", meaning: "حجرے" },
    bn: { name: "আল-হুজুরাত", meaning: "কক্ষসমূহ" },
    id: { name: "Al-Hujurat", meaning: "Kamar-Kamar" },
    ms: { name: "Al-Hujurat", meaning: "Bilik-Bilik" },
  },
  50: {
    hi: { name: "क़ाफ़", meaning: "क़ाफ़" },
    ru: { name: "Каф", meaning: "Буква Каф" },
    ur: { name: "قٓ", meaning: "قٓ" },
    bn: { name: "ক্বাফ", meaning: "ক্বাফ" },
    id: { name: "Qaf", meaning: "Qaf" },
    ms: { name: "Qaf", meaning: "Qaf" },
  },
  51: {
    hi: { name: "अज़-ज़ारियात", meaning: "बिखेरने वाली हवाएं" },
    ru: { name: "Аз-Зарийат", meaning: "Рассеивающие" },
    ur: { name: "الذاریات", meaning: "بکھیرنے والی ہوائیں" },
    bn: { name: "আয-যারিয়াত", meaning: "বিক্ষিপ্তকারী বাতাস" },
    id: { name: "Az-Zariyat", meaning: "Angin yang Menerbangkan" },
    ms: { name: "Az-Zariyat", meaning: "Angin yang Menerbangkan" },
  },
  52: {
    hi: { name: "अत-तूर", meaning: "तूर पर्वत" },
    ru: { name: "Ат-Тур", meaning: "Гора" },
    ur: { name: "الطور", meaning: "طور پہاڑ" },
    bn: { name: "আত-তূর", meaning: "তূর পর্বত" },
    id: { name: "At-Tur", meaning: "Bukit Tursina" },
    ms: { name: "At-Tur", meaning: "Bukit Tursina" },
  },
  53: {
    hi: { name: "अन-नज्म", meaning: "तारा" },
    ru: { name: "Ан-Наджм", meaning: "Звезда" },
    ur: { name: "النجم", meaning: "ستارہ" },
    bn: { name: "আন-নাজম", meaning: "নক্ষত্র" },
    id: { name: "An-Najm", meaning: "Bintang" },
    ms: { name: "An-Najm", meaning: "Bintang" },
  },
  54: {
    hi: { name: "अल-क़मर", meaning: "चांद" },
    ru: { name: "Аль-Камар", meaning: "Луна" },
    ur: { name: "القمر", meaning: "چاند" },
    bn: { name: "আল-ক্বামার", meaning: "চন্দ্র" },
    id: { name: "Al-Qamar", meaning: "Bulan" },
    ms: { name: "Al-Qamar", meaning: "Bulan" },
  },
  55: {
    hi: { name: "अर-रहमान", meaning: "परम कृपालु" },
    ru: { name: "Ар-Рахман", meaning: "Милостивый" },
    ur: { name: "الرحمٰن", meaning: "نہایت مہربان" },
    bn: { name: "আর-রহমান", meaning: "পরম করুণাময়" },
    id: { name: "Ar-Rahman", meaning: "Yang Maha Pengasih" },
    ms: { name: "Ar-Rahman", meaning: "Yang Maha Pemurah" },
  },
  56: {
    hi: { name: "अल-वाक़िआ", meaning: "घटित होने वाली घटना" },
    ru: { name: "Аль-Ваки'а", meaning: "Событие" },
    ur: { name: "الواقعہ", meaning: "واقع ہونے والی" },
    bn: { name: "আল-ওয়াক্বি'আহ", meaning: "অনিবার্য ঘটনা" },
    id: { name: "Al-Waqi'ah", meaning: "Hari Kiamat" },
    ms: { name: "Al-Waqi'ah", meaning: "Peristiwa Hari Kiamat" },
  },
  57: {
    hi: { name: "अल-हदीद", meaning: "लोहा" },
    ru: { name: "Аль-Хадид", meaning: "Железо" },
    ur: { name: "الحدید", meaning: "لوہا" },
    bn: { name: "আল-হাদীদ", meaning: "লোহা" },
    id: { name: "Al-Hadid", meaning: "Besi" },
    ms: { name: "Al-Hadid", meaning: "Besi" },
  },
  58: {
    hi: { name: "अल-मुजादिला", meaning: "तर्क करने वाली स्त्री" },
    ru: { name: "Аль-Муджадиля", meaning: "Препирающаяся" },
    ur: { name: "المجادلہ", meaning: "بحث کرنے والی" },
    bn: { name: "আল-মুজাদালাহ", meaning: "অনুযোগকারিণী" },
    id: { name: "Al-Mujadilah", meaning: "Gugatan" },
    ms: { name: "Al-Mujadilah", meaning: "Wanita yang Mengadu" },
  },
  59: {
    hi: { name: "अल-हश्र", meaning: "देशनिकाला / एकत्रण" },
    ru: { name: "Аль-Хашр", meaning: "Сбор" },
    ur: { name: "الحشر", meaning: "اکٹھا کرنا" },
    bn: { name: "আল-হাশর", meaning: "সমাবেশ" },
    id: { name: "Al-Hasyr", meaning: "Pengusiran" },
    ms: { name: "Al-Hasyr", meaning: "Pengusiran" },
  },
  60: {
    hi: { name: "अल-मुम्तहिना", meaning: "परखी जाने वाली स्त्री" },
    ru: { name: "Аль-Мумтахана", meaning: "Испытуемая" },
    ur: { name: "الممتحنہ", meaning: "امتحان لی گئی" },
    bn: { name: "আল-মুমতাহিনাহ", meaning: "পরীক্ষিত নারী" },
    id: { name: "Al-Mumtahanah", meaning: "Wanita yang Diuji" },
    ms: { name: "Al-Mumtahanah", meaning: "Perempuan yang Diuji" },
  },
  61: {
    hi: { name: "अस-सफ़", meaning: "पंक्ति / क़तार" },
    ru: { name: "Ас-Сафф", meaning: "Ряды" },
    ur: { name: "الصف", meaning: "صف" },
    bn: { name: "আস-সাফ", meaning: "সারিবদ্ধ সৈন্যদল" },
    id: { name: "As-Saff", meaning: "Barisan" },
    ms: { name: "As-Saff", meaning: "Barisan" },
  },
  62: {
    hi: { name: "अल-जुमुआ", meaning: "शुक्रवार" },
    ru: { name: "Аль-Джуму'а", meaning: "Пятница" },
    ur: { name: "الجمعہ", meaning: "جمعہ کا دن" },
    bn: { name: "আল-জুমু'আহ", meaning: "শুক্রবার" },
    id: { name: "Al-Jumu'ah", meaning: "Hari Jum'at" },
    ms: { name: "Al-Jumu'ah", meaning: "Hari Jumaat" },
  },
  63: {
    hi: { name: "अल-मुनाफ़िक़ून", meaning: "कपटाचारी" },
    ru: { name: "Аль-Мунафикун", meaning: "Лицемеры" },
    ur: { name: "المنافقون", meaning: "منافق لوگ" },
    bn: { name: "আল-মুনাফিকুন", meaning: "কপট বিশ্বাসীগণ" },
    id: { name: "Al-Munafiqun", meaning: "Orang-Orang Munafik" },
    ms: { name: "Al-Munafiqun", meaning: "Orang-Orang Munafik" },
  },
  64: {
    hi: { name: "अत-तग़ाबुन", meaning: "हार-जीत का दिन" },
    ru: { name: "Ат-Тагабун", meaning: "Раскрытие самообмана" },
    ur: { name: "التغابن", meaning: "ہار جیت" },
    bn: { name: "আত-তাগাবুন", meaning: "ক্ষতি-লাভ" },
    id: { name: "At-Taghabun", meaning: "Hari Ditampakkannya Kesalahan" },
    ms: { name: "At-Taghabun", meaning: "Hari Terbuka Kerugian" },
  },
  65: {
    hi: { name: "अत-तलाक़", meaning: "तलाक़" },
    ru: { name: "Ат-Талак", meaning: "Развод" },
    ur: { name: "الطلاق", meaning: "طلاق" },
    bn: { name: "আত-তালাক", meaning: "তালাক" },
    id: { name: "At-Talaq", meaning: "Perceraian" },
    ms: { name: "At-Talaq", meaning: "Perceraian" },
  },
  66: {
    hi: { name: "अत-तहरीम", meaning: "निषेध" },
    ru: { name: "Ат-Тахрим", meaning: "Запрещение" },
    ur: { name: "التحریم", meaning: "حرام ٹھہرانا" },
    bn: { name: "আত-তাহরীম", meaning: "নিষিদ্ধকরণ" },
    id: { name: "At-Tahrim", meaning: "Mengharamkan" },
    ms: { name: "At-Tahrim", meaning: "Mengharamkan" },
  },
  67: {
    hi: { name: "अल-मुल्क", meaning: "संप्रभुता / साम्राज्य" },
    ru: { name: "Аль-Мульк", meaning: "Власть" },
    ur: { name: "الملک", meaning: "بادشاہی" },
    bn: { name: "আল-মুলক", meaning: "সার্বভৌম কর্তৃত্ব" },
    id: { name: "Al-Mulk", meaning: "Kerajaan" },
    ms: { name: "Al-Mulk", meaning: "Kerajaan" },
  },
  68: {
    hi: { name: "अल-क़लम", meaning: "कलम" },
    ru: { name: "Аль-Калям", meaning: "Письменная трость" },
    ur: { name: "القلم", meaning: "قلم" },
    bn: { name: "আল-কলম", meaning: "কলম" },
    id: { name: "Al-Qalam", meaning: "Pena" },
    ms: { name: "Al-Qalam", meaning: "Pena" },
  },
  69: {
    hi: { name: "अल-हाक़्क़ा", meaning: "अटल सत्य" },
    ru: { name: "Аль-Хакка", meaning: "Неминуемое" },
    ur: { name: "الحاقہ", meaning: "سچ مچ ہونے والی" },
    bn: { name: "আল-হাক্কাহ", meaning: "নিশ্চিত সত্য" },
    id: { name: "Al-Haqqah", meaning: "Hari Kiamat" },
    ms: { name: "Al-Haqqah", meaning: "Peristiwa yang Benar" },
  },
  70: {
    hi: { name: "अल-मआरिज", meaning: "आरोहण की सीढ़ियां" },
    ru: { name: "Аль-Ма'аридж", meaning: "Ступени" },
    ur: { name: "المعارج", meaning: "عروج کی جگہیں" },
    bn: { name: "আল-মা'আরিজ", meaning: "উন্নয়নের সোপান" },
    id: { name: "Al-Ma'arij", meaning: "Tempat Naik" },
    ms: { name: "Al-Ma'arij", meaning: "Tempat-Tempat Naik" },
  },
  71: {
    hi: { name: "नूह", meaning: "हज़रत नूह" },
    ru: { name: "Нух", meaning: "Ной" },
    ur: { name: "نوح", meaning: "نوح علیہ السلام" },
    bn: { name: "নূহ", meaning: "নূহ (আঃ)" },
    id: { name: "Nuh", meaning: "Nabi Nuh" },
    ms: { name: "Nuh", meaning: "Nabi Nuh" },
  },
  72: {
    hi: { name: "अल-जिन्न", meaning: "जिन्न" },
    ru: { name: "Аль-Джинн", meaning: "Джинны" },
    ur: { name: "الجن", meaning: "جنات" },
    bn: { name: "আল-জ্বিন", meaning: "জিন জাতি" },
    id: { name: "Al-Jinn", meaning: "Jin" },
    ms: { name: "Al-Jinn", meaning: "Jin" },
  },
  73: {
    hi: { name: "अल-मुज़्ज़म्मिल", meaning: "कंबल ओढ़े हुए" },
    ru: { name: "Аль-Муззаммиль", meaning: "Закутавшийся" },
    ur: { name: "المزمل", meaning: "کمبل اوڑھنے والے" },
    bn: { name: "আল-মুযযাম্মিল", meaning: "বস্ত্রাচ্ছাদিত" },
    id: { name: "Al-Muzzammil", meaning: "Orang yang Berselimut" },
    ms: { name: "Al-Muzzammil", meaning: "Orang yang Berselimut" },
  },
  74: {
    hi: { name: "अल-मुद्दस्सिर", meaning: "चादर ओढ़े हुए" },
    ru: { name: "Аль-Муддассир", meaning: "Завернувшийся" },
    ur: { name: "المدثر", meaning: "چادر اوڑھنے والے" },
    bn: { name: "আল-মুদ্দাসসির", meaning: "চাদরাবৃত" },
    id: { name: "Al-Muddassir", meaning: "Orang yang Berkemul" },
    ms: { name: "Al-Muddatsir", meaning: "Orang yang Berselimut" },
  },
  75: {
    hi: { name: "अल-क़ियामा", meaning: "क़यामत / पुनरुत्थान" },
    ru: { name: "Аль-Кийама", meaning: "Воскресение" },
    ur: { name: "القیامہ", meaning: "قیامت کا دن" },
    bn: { name: "আল-ক্বিয়ামাহ", meaning: "পুনরুত্থান" },
    id: { name: "Al-Qiyamah", meaning: "Hari Berbangkit" },
    ms: { name: "Al-Qiyamah", meaning: "Hari Kiamat" },
  },
  76: {
    hi: { name: "अल-इंसान", meaning: "मनुष्य" },
    ru: { name: "Аль-Инсан", meaning: "Человек" },
    ur: { name: "الانسان", meaning: "انسان" },
    bn: { name: "আল-ইনসান", meaning: "মানবজাতি" },
    id: { name: "Al-Insan", meaning: "Manusia" },
    ms: { name: "Al-Insan", meaning: "Manusia" },
  },
  77: {
    hi: { name: "अल-मुरसलात", meaning: "भेजी गई हवाएं" },
    ru: { name: "Аль-Мурсалят", meaning: "Посылаемые" },
    ur: { name: "المرسلات", meaning: "بھیجی جانے والی ہوائیں" },
    bn: { name: "আল-মুরসালাত", meaning: "প্রেরিত বাতাস" },
    id: { name: "Al-Mursalat", meaning: "Malaikat yang Diutus" },
    ms: { name: "Al-Mursalat", meaning: "Malaikat yang Diutus" },
  },
  78: {
    hi: { name: "अन-नबा", meaning: "बड़ी ख़बर" },
    ru: { name: "Ан-Наба", meaning: "Весть" },
    ur: { name: "النباء", meaning: "بڑی خبر" },
    bn: { name: "আন-নাবা", meaning: "মহাসংবাদ" },
    id: { name: "An-Naba'", meaning: "Berita Besar" },
    ms: { name: "An-Naba'", meaning: "Berita Besar" },
  },
  79: {
    hi: { name: "अन-नाज़िआत", meaning: "खींचने वाले फ़रिश्ते" },
    ru: { name: "Ан-Нази'ат", meaning: "Исторгающие" },
    ur: { name: "النازعات", meaning: "کھینچنے والے" },
    bn: { name: "আন-নাযি'আত", meaning: "প্রবল টাননকারী" },
    id: { name: "An-Nazi'at", meaning: "Malaikat Pencabut" },
    ms: { name: "An-Nazi'at", meaning: "Malaikat yang Mencabut Roh" },
  },
  80: {
    hi: { name: "अबस", meaning: "माथे पर बल डाला" },
    ru: { name: "'Абаса", meaning: "Нахмурился" },
    ur: { name: "عبس", meaning: "تیوری چڑھائی" },
    bn: { name: "আবাসা", meaning: "তিনি ভ্রূকুটি করলেন" },
    id: { name: "'Abasa", meaning: "Ia Bermuka Masam" },
    ms: { name: "'Abasa", meaning: "Dia Bermasam Muka" },
  },
  81: {
    hi: { name: "अत-तकवीर", meaning: "लपेटा जाना" },
    ru: { name: "Ат-Таквир", meaning: "Скручивание" },
    ur: { name: "التکویر", meaning: "لپیٹ دیا جانا" },
    bn: { name: "আত-তাকওয়ীর", meaning: "অন্ধকারাচ্ছন্ন" },
    id: { name: "At-Takwir", meaning: "Menggulung" },
    ms: { name: "At-Takwir", meaning: "Menggulung" },
  },
  82: {
    hi: { name: "अल-इन्फ़ितार", meaning: "फटना" },
    ru: { name: "Аль-Инфитар", meaning: "Раскалывание" },
    ur: { name: "الانفطار", meaning: "پھٹ جانا" },
    bn: { name: "আল-ইনফিতার", meaning: "বিদীর্ণ হওয়া" },
    id: { name: "Al-Infitar", meaning: "Terbelah" },
    ms: { name: "Al-Infitar", meaning: "Terbelah" },
  },
  83: {
    hi: { name: "अल-मुतफ़्फ़िफ़ीन", meaning: "नाप-तोल में कमी करने वाले" },
    ru: { name: "Аль-Мутаффифин", meaning: "Обвешивающие" },
    ur: { name: "المطففین", meaning: "ناپ تول میں کمی کرنے والے" },
    bn: { name: "আল-মুতাফফিফীন", meaning: "প্রতারকগণ" },
    id: { name: "Al-Mutaffifin", meaning: "Orang-Orang yang Curang" },
    ms: { name: "Al-Mutaffifin", meaning: "Golongan yang Curang" },
  },
  84: {
    hi: { name: "अल-इन्शिकाक़", meaning: "टुकड़े-टुकड़े होना" },
    ru: { name: "Аль-Иншикак", meaning: "Разверзание" },
    ur: { name: "الانشقاق", meaning: "ٹکڑے ٹکڑے ہونا" },
    bn: { name: "আল-ইনশিক্বাক্ব", meaning: "খণ্ড-বিখণ্ড হওয়া" },
    id: { name: "Al-Insyiqaq", meaning: "Terbelah" },
    ms: { name: "Al-Insyiqaq", meaning: "Terbelah" },
  },
  85: {
    hi: { name: "अल-बुरुज", meaning: "नक्षत्र / बुर्ज" },
    ru: { name: "Аль-Бурудж", meaning: "Созвездия" },
    ur: { name: "البروج", meaning: "برج" },
    bn: { name: "আল-বুরুজ", meaning: "নক্ষত্রপুঞ্জ" },
    id: { name: "Al-Buruj", meaning: "Gugusan Bintang" },
    ms: { name: "Al-Buruj", meaning: "Gugusan Bintang" },
  },
  86: {
    hi: { name: "अत-तारिक़", meaning: "रात में आने वाला तारा" },
    ru: { name: "Ат-Тарик", meaning: "Ночной путник" },
    ur: { name: "الطارق", meaning: "رات کو آنے والا" },
    bn: { name: "আত-তারিক্ব", meaning: "রাত্রিকালীন আগন্তুক" },
    id: { name: "At-Tariq", meaning: "Yang Datang di Malam Hari" },
    ms: { name: "At-Tariq", meaning: "Bintang yang Menembusi" },
  },
  87: {
    hi: { name: "अल-आला", meaning: "सर्वोच्च" },
    ru: { name: "Аль-А'ля", meaning: "Всевышний" },
    ur: { name: "الاعلیٰ", meaning: "سب سے بلند" },
    bn: { name: "আল-আ'লা", meaning: "সর্বোচ্চ" },
    id: { name: "Al-A'la", meaning: "Yang Maha Tinggi" },
    ms: { name: "Al-A'la", meaning: "Yang Maha Tinggi" },
  },
  88: {
    hi: { name: "अल-ग़ाशिया", meaning: "छा जाने वाली आपदा" },
    ru: { name: "Аль-Гашийа", meaning: "Покрывающее" },
    ur: { name: "الغاشیہ", meaning: "چھا جانے والی آفت" },
    bn: { name: "আল-গাশিয়াহ", meaning: "আচ্ছন্নকারী বিপদ" },
    id: { name: "Al-Ghasyiyah", meaning: "Hari Pembalasan" },
    ms: { name: "Al-Ghasyiyah", meaning: "Peristiwa yang Menyelubungi" },
  },
  89: {
    hi: { name: "अल-फ़ज्र", meaning: "प्रातःकाल / भोर" },
    ru: { name: "Аль-Фаджр", meaning: "Заря" },
    ur: { name: "الفجر", meaning: "صبح کا وقت" },
    bn: { name: "আল-ফজর", meaning: "ভোর" },
    id: { name: "Al-Fajr", meaning: "Fajar" },
    ms: { name: "Al-Fajr", meaning: "Waktu Fajar" },
  },
  90: {
    hi: { name: "अल-बलद", meaning: "नगर / शहर" },
    ru: { name: "Аль-Баляд", meaning: "Город" },
    ur: { name: "البلد", meaning: "شہر" },
    bn: { name: "আল-বালাদ", meaning: "নগরী" },
    id: { name: "Al-Balad", meaning: "Negeri" },
    ms: { name: "Al-Balad", meaning: "Negeri" },
  },
  91: {
    hi: { name: "अश-शम्स", meaning: "सूर्य" },
    ru: { name: "Аш-Шамс", meaning: "Солнце" },
    ur: { name: "الشمس", meaning: "سورج" },
    bn: { name: "আশ-শামস", meaning: "সূর্য" },
    id: { name: "Asy-Syams", meaning: "Matahari" },
    ms: { name: "Asy-Syams", meaning: "Matahari" },
  },
  92: {
    hi: { name: "अल-लैल", meaning: "रात" },
    ru: { name: "Аль-Ляйль", meaning: "Ночь" },
    ur: { name: "اللیل", meaning: "رات" },
    bn: { name: "আল-লাইল", meaning: "রাত্রি" },
    id: { name: "Al-Lail", meaning: "Malam" },
    ms: { name: "Al-Lail", meaning: "Malam" },
  },
  93: {
    hi: { name: "अद-दुहा", meaning: "पूर्वाह्न / धूप" },
    ru: { name: "Ад-Духа", meaning: "Утро" },
    ur: { name: "الضحیٰ", meaning: "چاشت کا وقت" },
    bn: { name: "আদ-দুহা", meaning: "পূর্বাহ্নের রোদ" },
    id: { name: "Ad-Duha", meaning: "Waktu Dhuha" },
    ms: { name: "Ad-Dhuha", meaning: "Waktu Dhuha" },
  },
  94: {
    hi: { name: "अश-शरह", meaning: "राहत / सीने का खुलना" },
    ru: { name: "Аш-Шарх", meaning: "Раскрытие" },
    ur: { name: "الشرح", meaning: "سینے کا کھولنا" },
    bn: { name: "আশ-শারহ", meaning: "বক্ষ প্রশস্তকরণ" },
    id: { name: "Asy-Syarh", meaning: "Kelapangan" },
    ms: { name: "Asy-Syarh", meaning: "Kelapangan Dada" },
  },
  95: {
    hi: { name: "अत-तीन", meaning: "अंजीर" },
    ru: { name: "Ат-Тин", meaning: "Смоковница" },
    ur: { name: "التین", meaning: "انجیر" },
    bn: { name: "আত-তীন", meaning: "ডুমুর" },
    id: { name: "At-Tin", meaning: "Buah Tin" },
    ms: { name: "At-Tin", meaning: "Buah Tin" },
  },
  96: {
    hi: { name: "अल-अलक़", meaning: "जमा हुआ ख़ून" },
    ru: { name: "Аль-'Аляк", meaning: "Сгусток" },
    ur: { name: "العلق", meaning: "جما ہوا خون" },
    bn: { name: "আল-আলাক", meaning: "রক্তপিণ্ড" },
    id: { name: "Al-'Alaq", meaning: "Segumpal Darah" },
    ms: { name: "Al-'Alaq", meaning: "Segumpal Darah" },
  },
  97: {
    hi: { name: "अल-क़द्र", meaning: "महिमा / शक्ति की रात" },
    ru: { name: "Аль-Кадр", meaning: "Предопределение" },
    ur: { name: "القدر", meaning: "عظمت والی رات" },
    bn: { name: "আল-ক্বদর", meaning: "মহিমান্বিত রজনী" },
    id: { name: "Al-Qadr", meaning: "Kemuliaan" },
    ms: { name: "Al-Qadr", meaning: "Malam Kemuliaan" },
  },
  98: {
    hi: { name: "अल-बय्यिना", meaning: "स्पष्ट प्रमाण" },
    ru: { name: "Аль-Баййина", meaning: "Ясное знамение" },
    ur: { name: "البینہ", meaning: "روشن دلیل" },
    bn: { name: "আল-বায়্যিনাহ", meaning: "সুস্পষ্ট প্রমাণ" },
    id: { name: "Al-Bayyinah", meaning: "Bukti yang Nyata" },
    ms: { name: "Al-Bayyinah", meaning: "Bukti yang Nyata" },
  },
  99: {
    hi: { name: "अज़-ज़लज़ला", meaning: "भूकंप" },
    ru: { name: "Аз-Зальзаля", meaning: "Сотрясение" },
    ur: { name: "الزلزلہ", meaning: "زلزلہ" },
    bn: { name: "আয-যালযালাহ", meaning: "ভূমিকম্প" },
    id: { name: "Az-Zalzalah", meaning: "Kegoncangan" },
    ms: { name: "Az-Zalzalah", meaning: "Kegoncangan Bumi" },
  },
  100: {
    hi: { name: "अल-आदियात", meaning: "दौड़ने वाले घोड़े" },
    ru: { name: "Аль-'Адийат", meaning: "Мчащиеся" },
    ur: { name: "العادیات", meaning: "دوڑنے والے گھوڑے" },
    bn: { name: "আল-আদিয়াত", meaning: "অভিযানকারী অশ্ব" },
    id: { name: "Al-'Adiyat", meaning: "Kuda Perang Berlari Kencang" },
    ms: { name: "Al-'Adiyat", meaning: "Kuda Perang yang Berlari Pantas" },
  },
  101: {
    hi: { name: "अल-क़ारिआ", meaning: "खटखटाने वाली विपत्ति" },
    ru: { name: "Аль-Кари'а", meaning: "Великое бедствие" },
   ur: { name: "القارعہ", meaning: "کھڑکھڑانے والی" },
    bn: { name: "আল-ক্বারিয়া", meaning: "মহা বিপদ" },
    id: { name: "Al-Qari'ah", meaning: "Hari Kiamat yang Menggemparkan" },
    ms: { name: "Al-Qari'ah", meaning: "Hari Kiamat" },
  },
  102: {
    hi: { name: "अत-तकासुर", meaning: "अधिकता की होड़" },
    ru: { name: "Ат-Такасур", meaning: "Охота к умножению" },
    ur: { name: "التکاثر", meaning: "کثرت کی ہوس" },
    bn: { name: "আত-তাকাসুর", meaning: "প্রাচুর্যের প্রতিযোগিতা" },
    id: { name: "At-Takatsur", meaning: "Bermegah-Megahan" },
    ms: { name: "At-Takatsur", meaning: "Bermegah-Megahan" },
  },
  103: {
    hi: { name: "अल-असर", meaning: "ज़माना / समय" },
    ru: { name: "Аль-'Аср", meaning: "Время" },
    ur: { name: "العصر", meaning: "زمانہ" },
    bn: { name: "আল-আসর", meaning: "সময়" },
    id: { name: "Al-'Asr", meaning: "Masa" },
    ms: { name: "Al-'Asr", meaning: "Masa" },
  },
  104: {
    hi: { name: "अल-हुमज़ा", meaning: "चुग़लख़ोर / ताने देने वाला" },
    ru: { name: "Аль-Хумаза", meaning: "Хулитель" },
    ur: { name: "الہمزہ", meaning: "عیب جوئی کرنے والا" },
    bn: { name: "আল-হুমাযাহ", meaning: "পরনিন্দাকারী" },
    id: { name: "Al-Humazah", meaning: "Pengumpat" },
    ms: { name: "Al-Humazah", meaning: "Pengumpat" },
  },
  105: {
    hi: { name: "अल-फ़ील", meaning: "हाथी" },
    ru: { name: "Аль-Филь", meaning: "Слон" },
    ur: { name: "الفیل", meaning: "ہاتھی" },
    bn: { name: "আল-ফীল", meaning: "হাতি" },
    id: { name: "Al-Fil", meaning: "Gajah" },
    ms: { name: "Al-Fil", meaning: "Gajah" },
  },
  106: {
    hi: { name: "क़ुरैश", meaning: "क़ुरैश क़बीला" },
    ru: { name: "Курейш", meaning: "Курайшиты" },
    ur: { name: "قریش", meaning: "قریش" },
    bn: { name: "কুরাইশ", meaning: "কুরাইশ বংশ" },
    id: { name: "Quraisy", meaning: "Suku Quraisy" },
    ms: { name: "Quraisy", meaning: "Kaum Quraisy" },
  },
  107: {
    hi: { name: "अल-माऊन", meaning: "दैनिक उपयोग की वस्तुएं" },
    ru: { name: "Аль-Ма'ун", meaning: "Милостыня" },
    ur: { name: "الماعون", meaning: "عام ضرورت کی چیزیں" },
    bn: { name: "আল-মা'উন", meaning: "নিত্যপ্রয়োজনীয় সাহায্য" },
    id: { name: "Al-Ma'un", meaning: "Bantuan Berguna" },
    ms: { name: "Al-Ma'un", meaning: "Bantuan Berguna" },
  },
  108: {
    hi: { name: "अल-कौसर", meaning: "प्रचुर भलाई / कौसर" },
    ru: { name: "Аль-Кяусар", meaning: "Изобилие" },
    ur: { name: "الکوثر", meaning: "خیرِ کثیر" },
    bn: { name: "আল-কাওসার", meaning: "প্রচুর কল্যাণ" },
    id: { name: "Al-Kausar", meaning: "Nikmat yang Banyak" },
    ms: { name: "Al-Kautsar", meaning: "Kebaikan yang Banyak" },
  },
  109: {
    hi: { name: "अल-काफ़िरून", meaning: "इनकार करने वाले" },
    ru: { name: "Аль-Кафирун", meaning: "Неверующие" },
    ur: { name: "الکافرون", meaning: "کافر لوگ" },
    bn: { name: "আল-কাফিরুন", meaning: "অবিশ্বাসীগণ" },
    id: { name: "Al-Kafirun", meaning: "Orang-Orang Kafir" },
    ms: { name: "Al-Kafirun", meaning: "Orang-Orang Kafir" },
  },
  110: {
    hi: { name: "अन-नस्र", meaning: "ईश्वरीय सहायता" },
    ru: { name: "Ан-Наср", meaning: "Помощь" },
    ur: { name: "النصر", meaning: "اللہ کی مدد" },
    bn: { name: "আন-নাসর", meaning: "সাহায্য" },
    id: { name: "An-Nasr", meaning: "Pertolongan" },
    ms: { name: "An-Nasr", meaning: "Pertolongan" },
  },
  111: {
    hi: { name: "अल-मसद", meaning: "खजूर की रस्सी" },
    ru: { name: "Аль-Масад", meaning: "Пальмовые волокна" },
    ur: { name: "المسد", meaning: "بٹی ہوئی رسی" },
    bn: { name: "আল-মাসাদ", meaning: "খেজুরের আঁশের দড়ি" },
    id: { name: "Al-Lahab", meaning: "Gejolak Api" },
    ms: { name: "Al-Masad", meaning: "Tali Sabut" },
  },
  112: {
    hi: { name: "अल-इख़लास", meaning: "एकेश्वरवाद की निष्ठा" },
    ru: { name: "Аль-Ихляс", meaning: "Искренность" },
    ur: { name: "الاخلاص", meaning: "خالص توحید" },
    bn: { name: "আল-ইখলাস", meaning: "একনিষ্ঠতা" },
    id: { name: "Al-Ikhlas", meaning: "Kemurnian Keesaan Allah" },
    ms: { name: "Al-Ikhlas", meaning: "Keikhlasan Tauhid" },
  },
  113: {
    hi: { name: "अल-फ़लक़", meaning: "सवेरा" },
    ru: { name: "Аль-Фаляк", meaning: "Рассвет" },
    ur: { name: "الفلق", meaning: "صبح کا پھوٹنا" },
    bn: { name: "আল-ফালাক্ব", meaning: "ভোর" },
    id: { name: "Al-Falaq", meaning: "Waktu Subuh" },
    ms: { name: "Al-Falaq", meaning: "Waktu Subuh" },
  },
  114: {
    hi: { name: "अन-नास", meaning: "मानवजाति" },
    ru: { name: "Ан-Нас", meaning: "Люди" },
    ur: { name: "الناس", meaning: "تمام انسان" },
    bn: { name: "আন-নাস", meaning: "মানবজাতি" },
    id: { name: "An-Nas", meaning: "Manusia" },
    ms: { name: "An-Nas", meaning: "Manusia" },
  },
};

/**
 * Returns localized Surah name and meaning for the given chapter ID and language code.
 * Falls back to the provided fallback values (English) if no localization exists.
 */
export function getLocalizedSurah(
  id: number,
  language: string,
  fallbackName: string = "",
  fallbackMeaning: string = "",
): LocalizedSurahInfo {
  const entry = SURAH_LOCALIZED_DATA[id]?.[language];
  return {
    name: entry?.name || fallbackName,
    meaning: entry?.meaning || fallbackMeaning,
  };
}
